import { getServerSession } from 'next-auth';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import './globals.css';
import LoginBtn from './LoginBtn';
import LogoutBtn from './LogoutBtn';
import { authOptions } from '@/pages/api/auth/[...nextauth]';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  //현재 로그인된 유저이름, 이메일 등이 보여짐.
  let session = await getServerSession(authOptions); //pages/api/auth/[...nextauth.js의 변수가져와 사용]
  console.log(session);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <p className="logo">
            <Link href="/">LOGO</Link>
          </p>
          <p>
            <Link href="/list">list</Link>
          </p>
          <p>
            <Link href="/write">write</Link>
          </p>
          {session ? (
            <span style={{ color: '#fff' }}>
              {session.user.name} 님 <LogoutBtn />{' '}
            </span>
          ) : (
            <LoginBtn />
          )}

          {/*<LoginBtn></LoginBtn>
          <LogoutBtn></LogoutBtn> */}
          <p>
            <Link href="/register">회원가입</Link>
          </p>
        </div>
        {children}
      </body>
    </html>
  );
}
